spring.application.name=jwtproject
spring.datasource.url=mysql://avnadmin:<redacted>@mysql-32620937-gaurav-7826.h.aivencloud.com:27201/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_6MxNLszcn-tAiiDErBs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=27201

sarvam.api.key=sk_3n1dvc03_O4vzvNExUCVZfdRuELUUHi7N
sarvam.model="sarvam-105b"